### ISSUE TITLE
`attributes_list` seems to be working only if `attributes is set`

### ISSUE THREAD

**Issue by rrey** [octo-technology/keycloak-collection#14]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

keycloak_group

##### SUMMARY

During tests conversion I had this code:

```
  keycloak_group:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: master
    realm: "master"
    name: "test_create_group_with_attibutes_dict"
#    attributes:
#      attr1: ["value1"]
#      attr2: ["value2"]
    attributes_list:
    - name: "attr1"
      value: "value1"
    - name: "attr2"
      value: "value2"
    - name: "attr3"
      value: "value3"
    realmRoles:
    - "uma_authorization"
    clientRoles:
    - clientid: "master-realm"
      roles:
        - "manage-users"
        - "view-identity-providers"
    state: "present"
  register: result
```

I had already called the module without `attributes_list` and `attributes` uncommented.
I expected that the `attr3` attribute would show up but it did not.
I had to uncomment the `attributes` block to have the expected result.
