### ISSUE TITLE
keycloak_role fails with composite role

### ISSUE THREAD

**Issue by rrey** [octo-technology/keycloak-collection#17]
##### SUMMARY

Composite role creation is failing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

keycoak_role

##### STEPS TO REPRODUCE

```yaml
- name: create a role
  keycloak_role:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: "master"
    realm: "master"
    name: "test_modify_role_two_client_role_with_same_name"
    description: "Test modify role two client roles with same name"
    composite: True
    composites:
      - name: "admin"
        clientId: "test2"
      - name: "manager"
        clientId: "test2"
    state: "present"
  register: result
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

```paste below
TASK [keycloak_role : create a role] ************************************************************************************************************************************************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unable to get client 620d9911-bd37-485b-832b-2acab3012622 role ******** in realm master: HTTP Error 404: Not Found"}
```
